# coding: utf-8

"""
    Dam Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dam.models.dam_list_assets_response import DamListAssetsResponse

class TestDamListAssetsResponse(unittest.TestCase):
    """DamListAssetsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DamListAssetsResponse:
        """Test DamListAssetsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DamListAssetsResponse`
        """
        model = DamListAssetsResponse()
        if include_optional:
            return DamListAssetsResponse(
                assets = [
                    dam.models.dam_asset.damAsset(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        id = '', 
                        type = 'UNKNOWN', 
                        code = '', 
                        metadata = [
                            dam.models.asset_metadata.AssetMetadata(
                                key = '', 
                                value = '', )
                            ], 
                        grn = '', 
                        public_url = '', )
                    ],
                next_page_token = ''
            )
        else:
            return DamListAssetsResponse(
        )
        """

    def testDamListAssetsResponse(self):
        """Test DamListAssetsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
