# coding: utf-8

"""
    Dam Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dam.models.update_asset_request_payload import UpdateAssetRequestPayload

class TestUpdateAssetRequestPayload(unittest.TestCase):
    """UpdateAssetRequestPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateAssetRequestPayload:
        """Test UpdateAssetRequestPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateAssetRequestPayload`
        """
        model = UpdateAssetRequestPayload()
        if include_optional:
            return UpdateAssetRequestPayload(
                code = '',
                origin = dam.models.dam_asset_origin.damAssetOrigin(
                    url = '', 
                    type = 'EXTERNAL', ),
                metadata = [
                    dam.models.asset_metadata.AssetMetadata(
                        key = '', 
                        value = '', )
                    ]
            )
        else:
            return UpdateAssetRequestPayload(
                origin = dam.models.dam_asset_origin.damAssetOrigin(
                    url = '', 
                    type = 'EXTERNAL', ),
        )
        """

    def testUpdateAssetRequestPayload(self):
        """Test UpdateAssetRequestPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
