# coding: utf-8

"""
    Dam Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dam.models.dam_get_asset_by_code_request import DamGetAssetByCodeRequest

class TestDamGetAssetByCodeRequest(unittest.TestCase):
    """DamGetAssetByCodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DamGetAssetByCodeRequest:
        """Test DamGetAssetByCodeRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DamGetAssetByCodeRequest`
        """
        model = DamGetAssetByCodeRequest()
        if include_optional:
            return DamGetAssetByCodeRequest(
                tenant_id = '',
                code = ''
            )
        else:
            return DamGetAssetByCodeRequest(
                tenant_id = '',
                code = '',
        )
        """

    def testDamGetAssetByCodeRequest(self):
        """Test DamGetAssetByCodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
