# coding: utf-8

"""
    Dam Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dam.models.asset_origin_types import AssetOriginTypes

class TestAssetOriginTypes(unittest.TestCase):
    """AssetOriginTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetOriginTypes(self):
        """Test AssetOriginTypes"""
        # inst = AssetOriginTypes()

if __name__ == '__main__':
    unittest.main()
