# coding: utf-8

"""
    Dam Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dam.api.basic_operations_api import BasicOperationsApi


class TestBasicOperationsApi(unittest.TestCase):
    """BasicOperationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BasicOperationsApi()

    def tearDown(self) -> None:
        pass

    def test_batch_upload_assets(self) -> None:
        """Test case for batch_upload_assets

        Batch Upload Assets
        """
        pass

    def test_batch_upload_assets_0(self) -> None:
        """Test case for batch_upload_assets_0

        Batch Upload Assets
        """
        pass

    def test_create_asset(self) -> None:
        """Test case for create_asset

        Create Asset
        """
        pass

    def test_create_asset_0(self) -> None:
        """Test case for create_asset_0

        Create Asset
        """
        pass

    def test_get_asset_by_code(self) -> None:
        """Test case for get_asset_by_code

        Get Asset By Code
        """
        pass

    def test_get_asset_by_code_0(self) -> None:
        """Test case for get_asset_by_code_0

        Get Asset By Code
        """
        pass

    def test_list_assets(self) -> None:
        """Test case for list_assets

        List Assets
        """
        pass

    def test_list_assets_0(self) -> None:
        """Test case for list_assets_0

        List Assets
        """
        pass

    def test_list_assets_by_codes(self) -> None:
        """Test case for list_assets_by_codes

        List Assets By Codes
        """
        pass

    def test_list_assets_by_codes_0(self) -> None:
        """Test case for list_assets_by_codes_0

        List Assets By Codes
        """
        pass

    def test_list_assets_by_ids(self) -> None:
        """Test case for list_assets_by_ids

        List Assets By Ids
        """
        pass

    def test_list_assets_by_ids_0(self) -> None:
        """Test case for list_assets_by_ids_0

        List Assets By Ids
        """
        pass

    def test_update_asset(self) -> None:
        """Test case for update_asset

        Update Asset
        """
        pass

    def test_update_asset_0(self) -> None:
        """Test case for update_asset_0

        Update Asset
        """
        pass


if __name__ == '__main__':
    unittest.main()
