# coding: utf-8

"""
    Dam Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dam.models.dam_asset_type import DamAssetType

class TestDamAssetType(unittest.TestCase):
    """DamAssetType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDamAssetType(self):
        """Test DamAssetType"""
        # inst = DamAssetType()

if __name__ == '__main__':
    unittest.main()
