# coding: utf-8

"""
    Dam Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DamAssetType(str, Enum):
    """
    DamAssetType
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    IMAGE = 'IMAGE'
    VIDEO = 'VIDEO'
    VIDEO_EXTERNAL = 'VIDEO_EXTERNAL'
    APPLICATION = 'APPLICATION'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DamAssetType from a JSON string"""
        return cls(json.loads(json_str))


