# coding: utf-8

# flake8: noqa

"""
    Dam Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.3.0"

# import apis into sdk package
from dam.api.basic_operations_api import BasicOperationsApi

# import ApiClient
from dam.api_response import ApiResponse
from dam.api_client import ApiClient
from dam.configuration import Configuration
from dam.exceptions import OpenApiException
from dam.exceptions import ApiTypeError
from dam.exceptions import ApiValueError
from dam.exceptions import ApiKeyError
from dam.exceptions import ApiAttributeError
from dam.exceptions import ApiException

# import models into sdk package
from dam.models.asset_metadata import AssetMetadata
from dam.models.asset_origin_types import AssetOriginTypes
from dam.models.batch_upload_assets_request_files import BatchUploadAssetsRequestFiles
from dam.models.dam_asset import DamAsset
from dam.models.dam_asset_origin import DamAssetOrigin
from dam.models.dam_asset_type import DamAssetType
from dam.models.dam_batch_upload_assets_request import DamBatchUploadAssetsRequest
from dam.models.dam_batch_upload_assets_response import DamBatchUploadAssetsResponse
from dam.models.dam_create_asset_request import DamCreateAssetRequest
from dam.models.dam_get_asset_by_code_request import DamGetAssetByCodeRequest
from dam.models.dam_list_assets_by_codes_request import DamListAssetsByCodesRequest
from dam.models.dam_list_assets_by_codes_response import DamListAssetsByCodesResponse
from dam.models.dam_list_assets_by_ids_request import DamListAssetsByIdsRequest
from dam.models.dam_list_assets_by_ids_response import DamListAssetsByIdsResponse
from dam.models.dam_list_assets_request import DamListAssetsRequest
from dam.models.dam_list_assets_response import DamListAssetsResponse
from dam.models.dam_update_asset_request import DamUpdateAssetRequest
from dam.models.protobuf_any import ProtobufAny
from dam.models.rpc_status import RpcStatus
from dam.models.update_asset_request_payload import UpdateAssetRequestPayload
